### PR TITLE
Prepare dev environment to new version

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

The PR removes non functional changes from #131 so that we can get new dev environment fast without waiting #131. This is more convenient and open door for active experimenting with new APIs and cmdlet drafts.

### CODE REVIEW

**Comment by iSazonov** [comment]
@SteveL-MSFT  @ayousuf23 Who could review this?

**Comment by ayousuf23** [comment]
I don't think I'm the best person to review this. Let's see what @SeeminglyScience or @anmenaga says.

**Comment by iSazonov** [comment]
@SeeminglyScience  @anmenaga can you merge this?

**Comment by ayousuf23** [comment]
@iSazonov Since the master branch has been updated, you might want to consider closing this PR.

**Comment by iSazonov** [comment]
I'd prefer to add .editorconfig since we switch to C#.

**Pull request closed without merging**
