### PR TITLE
Make $DestinationPath a mandatory parameter

### PR DESCRIPTION
**Pull request by sdwheeler**
Was set to false but had ValidateNotNullOrEmpty attribute making it required.

### CODE REVIEW

**Comment by sdwheeler** [comment]
@SteveL-MSFT Who can review and merge this change?

**Comment by anmenaga** [comment]
It doesn't looks like a proper thing to do...
As far as I know `mandatory=$false` and `ValidateNotNullOrEmpty` are Not mutually exclusive.
The `ValidateNotNullOrEmpty` validation just checks the supplied parameter to verify that it is not null or empty. If the parameter is not supplied at all there is nothing to check.
Current public interface of the cmdlet is that `DestinationPath` parameter is optional.
Making it mandatory is a breaking change (as indicated by test failures in AppVeyor).

**Comment by sdwheeler** [comment]
@anmenaga The problem is that the docs say that it is mandatory and if you omit the parameter, you get prompted for a value.

**Comment by sdwheeler** [comment]
@anmenaga Nevermind. I tested this again and didn't get prompted. I will fix the docs.

**Comment by SteveL-MSFT** [comment]
@sdwheeler when we talked, you indicated that you get prompted for `DestinationPath`, but that isn't the case.  I just tried it and if you don't specify `-DestinationPath`, it uses the current working directory which is what I expected.  This seems to be working as designed.

**Pull request closed without merging**
