### PR TITLE
Only write cross platform compatible directory separators in Compress-Archive

### LINKED ISSUE #11: `Compress-Archive` on Windows PowerShell generates an archive incompatible with OS X Archiver
See https://github.com/PowerShell/PowerShell/issues/2140 for details

### PR DESCRIPTION
**Pull request by mryanmurphy**
This resolves #11 and #48 

The approach taken is leveraging the fact that .net on Windows all the way back to Framework 1.1 specifies `\` as DirectoryPathSeparatorChar and `/` as AltDirectoryPathSeparatorChar, while other platforms in .net Core use `/` for DirectoryPathSeparatorChar and AltDirectoryPathSeparatorChar.

When using a *nix platform, the replacements will be no-ops, while Windows will convert all `\` to `/` for the purposes of the ZipEntry FullName.

### CODE REVIEW

**Comment by mryanmurphy** [comment]
Not sure who the maintainers of the repo are, so this has been waiting for quite some time. As top contributor @anmenaga, is there anything I can do to get some visibility?

**Comment by SteveL-MSFT** [comment]
@mryanmurphy we appreciate your contribution.  Sorry about the delay.  @anmenaga can you review this?

**Comment by mryanmurphy** [comment]
Thanks for the feedback all, I believe I addressed each point.

**Comment by mryanmurphy** [comment]
@anmenaga @SteveL-MSFT Let me know if there's anything else I can do to get this merged. Thanks!

**Comment by mikebridge** [comment]
Is there a workaround for the separator issue until version 1.2.3 is generally available?

**Comment by mikebridge** [comment]
```bash

**Comment by mryanmurphy** [comment]
I'm not sure how often they push changes to PSGallery. Since opening the PR I've had the fixed module on my machines with a `#Requires -Modules @{ ModuleName="Microsoft.PowerShell.Archive"; ModuleVersion="1.2.3.0" }` statement on scripts involving archives. Downloading the source and moving the `Microsoft.PowerShell.Archive` folder to `~/Documents/WindowsPowerShell/Modules` and `~/Documents/PowerShell/Modules` has worked for me. 

Besides that I think the only workaround would be to not use this module for cross platform archiving.

**Comment by mikebridge** [comment]
I since discovered that `tar` on windows is a thing: 

https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/

That works better for what I'm trying to do, which is extract archives on linux machines.

**Comment by mikemaccana** [comment]
`Compress-Archive` still does not write cross platform directory separators on Powershell 6.2

Is `compress-archive` part of Powershell itself, i.e should 6.2 should include this fix?

If so there seems to be more issues with directory separators:

https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/71

**Comment by mikemaccana** [comment]
Hrm it seems 6.2 still ships with the broken `compress-archive`:

```
get-Module Microsoft.PowerShell.Archive

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.2.2.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Archive}
```

And I can't update it:

```
Update-Module Microsoft.PowerShell.Archive
Update-Module : Module 'Microsoft.PowerShell.Archive' was not installed by using Install-Module, so it cannot be updated.
```

How can we get our hands on the fix?

**Comment by mryanmurphy** [comment]
@SteveL-MSFT is there a process to get version 1.2.3.0 deployed to PS Gallery?

**Comment by SteveL-MSFT** [comment]
@anmenaga is working on publishing new version of Archive module to PSGallery.  Unfortunately, we missed this and didn't get it into 6.2.  Perhaps we can pick it up for a future 6.2.x servicing release.

**Comment by mryanmurphy** [comment]
Looks like it got into 6.2.1 today from https://github.com/PowerShell/PowerShell/pull/9594, and updated in PSGallery last week https://www.powershellgallery.com/packages/Microsoft.PowerShell.Archive/1.2.3.0

Thanks.

**Pull request merged**
